name: Mobirise Cleanup

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run cleanup script
        run: python .github/scripts/cleanup.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated cleanup: remove Mobirise branding, fix scripts, pretty URLs" || echo "No changes to commit"
          git push 